### PR TITLE
Update admin_groups.php

### PR DESCRIPTION
**Pull request by pkessanidis**
'Mod promote users label' & 'Mod promote users help' have been added.

### CODE REVIEW

**Comment by oldskool** [comment]
Thanks for this. Could you indent the text with tabs (instead of spaces) like in the rest of the file?

**Comment by pkessanidis** [comment]
Yes of course and thanks for the advice! But I still can't stand github..

**Comment by pkessanidis** [comment]
Could you please merge that request?

**Comment by franzliedke** [comment]
I merged this [as one commit](https://github.com/fluxbb/langs/commit/cc52bbedc2062dc46082b819bbe037f33ca21c36) - thank you!

**Pull request closed without merging**
